import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {  setIsLoading(false) }, 500);
  }, [])

  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!!!!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}

    {isLoading && 
      <>
      <div className="preloader-area">
        <div className='coin'>
          <div className='front jump'>
            <div className='star'></div>
            <span className='currency'>
              <i className="las la-coins"></i>
            </span>
            <div className='shapes'>
              <div className='shape_l'></div>
              <div className='shape_r'></div>
              <span className='top'>Stay Fit</span>
              <span className='bottom'>Stay Fit</span>
            </div>
          </div>
          <div className='shadow'></div>
        </div>
      </div>
      </>
    }
    <header className="header-section">
      <div className="header">
        <div className="header-top-area">
          <div className="container">
            <div className="header-top-content">
              <div className="header-content d-flex flex-wrap justify-content-between align-items-center">
                <div className="header-right-info">
                  <span className="first-info">
                     <Link href="tel:+ 001 2166 5645">
                        <a>
                          <i className="fas fa-phone"></i>{`+ 001 2166 5645`}
                        </a>
                     </Link> 
                  </span>
                </div>
                <div className="header-right-info">
                  <div className="header-action">
                    <Link href="#"><a className="cmn-btn-active">Login</a></Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="header-bottom-area">
          <div className="container">
            <div className="header-menu-content">
              <nav className="navbar navbar-expand-lg p-0">
                <Link href="/">
                  <a className="site-logo site-title">
                  <Image src="https://web3wellness.fit/assets/images/logoIcon/logo.png" alt="site-logo" layout="fill" objectFit="contain" />
                  </a>
                </Link>
                <button className="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span className="fas fa-bars"></span>
                </button>
                <div className="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul className="navbar-nav main-menu ml-auto mr-auto">
                    <li>
                      <Link href="/"><a className="active">Home</a></Link>
                    </li>
                    <li>
                      <Link href="/privacy"><a className="active">Privacy Policy</a></Link>
                    </li>
                    <li>
                      <Link href="/terms-condition"><a className="active">Terms & Conditions</a></Link>
                    </li>
                  </ul>
                </div>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </header>
    <section className="banner-section bg-overlay-primary bg_img" data-background="assets/images/frontend/banner/3.jpg">
      <div className="container">
        <div className="row justify-content-center align-items-center ml-b-30">
          <div className="col-lg-10 text-center mrb-30">
            <div className="banner-content">
              <h2 className="title">we reward you to stay healthy</h2>
              <p>You will get a reward in the form of our crypto token JW. We will also introduce workout plans, and diet plans later in paid monthly plans. This is a pure fitness app that will sell its memberships in JW tokens and give rewards to its users in the form of JW tokens.</p>
              <div className="banner-btn justify-content-center">
                {/* <Link href="https://accounts.google.com/o/oauth2/auth?response_type=code&amp;access_type=offline&amp;client_id=870456902994-ok6pbosd1pt83qav2jc1lo7fkd6b7kd6.apps.googleusercontent.com&amp;redirect_uri=https%3A%2F%2Fwww.web3wellness.fit%2Fauth%2Fgoogle%2Fcallback&amp;state&amp;scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffitness.activity.read%20profile%20email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts.other.readonly&amp;prompt=select_account%20consent">
                  <Image src="../developers.google.com/identity/images/btn_google_signin_dark_normal_web.png" />
                </Link> */}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="particles-js"></div>
    </section>
    <div className="privacy-area privacy-area--style d-none d-lg-block">
      <div className="container">
        <div className="copyright-area d-flex flex-wrap align-items-center justify-content-center">
          <div className="copyright">
            <p>COPYRIGHT © 2022 ALL RIGHTS RESERVED</p>
          </div>
        </div>
      </div>
    </div>
      
    </div>
  )
}
